analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
include: package:pedantic_mono/analysis_options.yaml

linter:
  rules:
    depend_on_referenced_packages: true
    prefer_relative_imports: true
    always_put_control_body_on_new_line: false